version: '3.5'

services:

  backend:
    container_name: "investmap_back"
    build:
      context: ../investmap_back/
      dockerfile: ../investmap_back/Dockerfile
    command: bash -c "
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:create db:migrate &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    
  postgres:
    container_name: "postgres"
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.app_data:/var/lib/postgresql/data

  frontend:
    container_name: "investmap_front"
    image: node:16-alpine
    restart: always
    command: > 
      sh -c "
        echo '--------- INSTALL NODE MODULES' &&
        yarn &&
        echo '--------- START UI SERVER FOR DEVELOPMENT' &&
        yarn dev
        "
    volumes:
      - ../investmap_front:/usr/src/app/
    working_dir: /usr/src/app
    ports:
      - "8000:3000"

  pgadmin:
    container_name: "pgadmin"
    image: fenglc/pgadmin4
    # environment:
    #   DEFAULT_USER: "admin@admin.com.br"
    #   DEFAULT_PASSWORD: "123456"
    ports:
      - "8080:5050"